export const PROCRASTINATION_TYPE = [
  'NOTDEFINED',
  'SUPERPROCRASTINATOR',
  'PERFECTIONIST',
  'DISORGANIZED',
  'ANTIPROCRASTINATOR',
];

export const SPECIALIZATION_STATE = [
  'INCUBATION',
  'TODO',
  'TODO_LATE',
  'WAITING',
  'WAITING_LATE',
  'DOING',
  'DOING_LATE',
  'COMPLETED',
  'COMPLETED_LATE',
  'PAUSED',
  'PAUSED_LATE',
  'DELETED',
];

export const SECTION_NAMES = [
  'ATRASADOS',
  'PRIORIDADE MAX/URG',
  'HOJE',
  'PROXIMOS 7 DIAS',
];

export const ACTIVITY_TYPE = [
  'ACTIVITY',
  'TASK',
  'PROJECT',
  'HABIT',
  'GOAL',
  'PLANNING',
];
